#!/usr/bin/env python

import os
from abjad.tools import iotools
from abjad.cfg.cfg import EXPERIMENTALPATH
from abjad.tools.documentationtools import AbjadAPIGenerator


if __name__ == '__main__':

    class ExperimentalAPIGenerator(AbjadAPIGenerator):

        @property
        def code_tools_path(self):
            return EXPERIMENTALPATH

        @property
        def docs_api_index_path(self):
            return os.path.join(EXPERIMENTALPATH, 'docs', 'source', 'index.rst')

        @property
        def docs_tools_path(self):
            return os.path.join(EXPERIMENTALPATH, 'docs', 'source', 'experimental')

        @property
        def package_prefix(self):
            return 'experimental.'

        @property
        def root_package(self):
            return 'experimental'

        @property
        def tools_package_path_index(self):
            return 1

    ExperimentalAPIGenerator()(verbose=True)

    # print greeting
    print 'Now building the Experimental HTML docs ...'
    print ''

    # change to docs directory because makefile lives there
    docs_directory = os.path.join(EXPERIMENTALPATH, 'docs')
    os.chdir(docs_directory)

    # make html docs
    iotools.spawn_subprocess('make html')
