#!/usr/bin/env python


from abjad.tools import iotools
from experimental import abjadbooktools
import getopt
import os
import sys


def _usage():
    usage = '''NAME
abjad-book -- preprocess HTML, LaTeX or ReST source with Abjad

SYNOPSIS 
    abjad-book [--skip-rendering] INPUT OUTPUT 

OPTIONS
    --skip-rendering
        when give, abjad-book will skip all image rendering and simply execute
        the code and write its output to OUTPUT.
    '''
    return usage


def _abjad_book():

    # get input parameters
    try:
        opts, args = getopt.getopt(sys.argv[1:], '', ['skip-rendering'])
    except getopt.GetoptError, err:
        print str(err)
        print _usage( )
        sys.exit(2)

    # parse commandline options
    skip_rendering = False
    for o, a in opts:
       if o == '--skip-rendering':
           skip_rendering = True
       else:
           assert False, 'unhandled option'

    # get input and output files
    if len(args) < 2:
        print _usage( )
        sys.exit(2)
    input_filename = args[0]
    output_filename = args[1]

    print "Processing '%s' ...." % input_filename
    print "Will write output to '%s'..." % output_filename

    # get directory of input file, and read out lines
    directory = os.path.abspath(os.path.dirname(input_filename))
    with open(input_filename, 'r') as f:
        lines = f.read().split('\n')
    
    # create output formatter and abjad-book processor
    file_extension = '.{}'.format(output_filename.rpartition('.')[-1])
    output_formats = {
        '.htm': abjadbooktools.HTMLOutputFormat,
        '.html': abjadbooktools.HTMLOutputFormat,
        '.rst': abjadbooktools.ReSTOutputFormat,
        '.tex': abjadbooktools.LaTeXOutputFormat,
    }
    if file_extension not in output_formats:
        raise ValueError('Unknown filetype for {!r}.'.format(output_filename))
    output_format = output_formats[file_extension]()
    abjad_book_processor = abjadbooktools.AbjadBookProcessor(lines, output_format, skip_rendering)

    # open and write to output file
    file = open(output_filename, 'w')
    file.writelines(abjad_book_processor(directory))
    file.close( )    


if __name__ == '__main__':
    iotools.clear_terminal()
    _abjad_book()
