#! /usr/bin/env python
import sys
from experimental.tools import scoremanagementtools


studio = scoremanagementtools.studio.Studio()
studio.session.dump_transcript = True
studio.run(user_input=' '.join(sys.argv[1:]))
