#! /usr/bin/env python
import sys
from experimental.tools import scoremanagertools


studio = scoremanagertools.scoremanager.ScoreManager()
studio.session.dump_transcript = True
studio.run(user_input=' '.join(sys.argv[1:]))
