#! /usr/bin/env python

import os
import sys
from abjad import abjad_configuration
from abjad.tools import iotools


start_directory = os.path.abspath('.')
os.chdir(abjad_configuration.abjad_directory_path)
iotools.clear_terminal()
command = 'grep -Irn "{}" * | grep -v svn\/ | grep -v docs'.format(sys.argv[1])
iotools.spawn_subprocess(command)
os.chdir(start_directory)
