#! /usr/bin/env python

from abjad.cfg.cfg import ABJADPATH
from abjad.tools import iotools
import os
import sys


start_directory = os.path.abspath('.')
os.chdir(ABJADPATH)
iotools.clear_terminal()
os.system('grep -Irn "%s" * | grep -v svn | grep -v docs' % sys.argv[1])
os.chdir(start_directory)
