#! /usr/bin/env python

from abjad.tools import iotools
import sys


iotools.clear_terminal()
command = 'grep -Irn "{}" * | grep -v svn | grep -v documentation | grep -v test'.format(sys.argv[1])
iotools.spawn_subprocess(command)
