#! /usr/bin/env python

import os
from abjad.cfg.cfg import ABJADPATH
from abjad.tools import iotools
from abjad.tools.iotools._write_abjad_version_file import _write_abjad_version_file
from abjad.tools.iotools.remove_abjad_pyc_files import remove_abjad_pyc_files


## find start directory and project root
start_directory = os.path.abspath('.')
project_root = ABJADPATH.rstrip('abjad')

## svn update
os.chdir(project_root)
iotools.clear_terminal( )
os.system('svn update')
os.chdir(start_directory)

## write version file
_write_abjad_version_file( )

## remove Abjad *.pyc files
remove_abjad_pyc_files( )
