#! /usr/bin/env python

from abjad.tools import iotools
import os
import sys


iotools.clear_terminal()
os.system(
   'grep -Irn "%s" `find . -name test_*` | grep -v svn | grep -v documentation'
   % sys.argv[1])
