#! /usr/bin/env python

from abjad.tools import iotools
import subprocess
import sys


iotools.clear_terminal()
command = 'grep -Irn "{}" `find . -name test_*` | grep -v svn | grep -v documentation'.format(sys.argv[1])
iotools.spawn_subprocess(command)
