#! /usr/bin/env python

from abjad.cfg.cfg import ABJADPATH
from abjad.tools import iotools
from abjad.tools.iotools._update_docs_release_string import _update_docs_release_string
import os


# find start directory and project root
start_directory = os.path.abspath('.')
project_root = ABJADPATH.rstrip('abjad')

# svn update
os.chdir(project_root)
iotools.clear_terminal()
os.system('svn update')
os.chdir(start_directory)

# remove Abjad *.pyc files
iotools.remove_abjad_pyc_files()
