#! /usr/bin/env python

from abjad.tools import iotools
import os
import sys


iotools.clear_terminal()
os.system(
   'grep -Irn "%s" * | grep -v svn | grep -v documentation | grep -v test' % 
   sys.argv[1])
