#! /usr/bin/env python

import sys
from abjad.tools import iotools


iotools.clear_terminal()
command = r'grep -Irn {!r} * | grep -v svn-base | grep -v svn\/ | grep -v docs'.format(sys.argv[1])
iotools.spawn_subprocess(command)
