#! /usr/bin/env python

from abjad.cfg.cfg import ABJADPATH
import os


def _find_initializers( ):
   initializers = [ ]
   for path, subdirectories, files in os.walk(ABJADPATH):
      for f in files:
         if f == '__init__.py':
            parent_directory = path.split(os.sep)[-1]
            ## protect abjad/__init__.py
            if parent_directory not in ('abjad', ):
               initializers.append(os.path.join(path, f))
   print 'There are %s initializers ...' % len(initializers)
   total_manual_imports = 0
   for x in initializers:
      kept_lines = [ ]
      for line in file(x, 'r').readlines( ):
         if line.startswith('from ') and line[5].isupper( ):
            total_manual_imports += 1
         else:
            kept_lines.append(line)
      file(x, 'w').write(kept_lines)
      
   print 'Total manual imports: %s' % total_manual_imports

if __name__ == '__main__':
   os.system('clear')
   print 'Finding manual class loads in initializers ...'
   _find_initializers( )
