#! /usr/bin/env python

from abjad import ABJCFG
from abjad.tools import clear_terminal
import os


def _find_initializers():
   public_class_package_initializers = [ ]
   for path, subdirectories, files in os.walk(ABJCFG.ABJAD_PATH):
      for f in files:
         if f == '__init__.py':
            initializer_parent_directory = path.split(os.path.sep)[-1]
            if initializer_parent_directory[0].isupper():
               public_class_package_initializers.append(os.path.join(path, f))
   print 'There are %s public class packages ...' % len(public_class_package_initializers)
   for x in public_class_package_initializers:
      first_line = file(x, 'r').readlines()[0]
      if 'importtools' not in first_line:
         output = file(x, 'w')
         output.write('from abjad.tools import importtools\n')
         output.write('\n')
         output.write('importtools.import_structured_package(__path__[0], globals())\n')
         output.close()
      

if __name__ == '__main__':
   iotools.clear_terminal()
   print 'Finding manual class package initializers ...'
   _find_initializers()
