#! /usr/bin/env python

import os
import re
from abjad import ABJCFG
from abjad.tools import iotools


def _find_lower_camel_case_modules():
    lower_camel_case_modules = [ ]
    lower_camel_case_pattern = re.compile(r'[a-z]+[A-Z]+.*')
    for path, subdirectories, file_names in os.walk('.'):
        for file_name in file_names:
            found_import_as_statement = False
            if file_name.endswith('.py'):
                short_name = file_name[:-3]
                if lower_camel_case_pattern.match(short_name):
                    lower_camel_case_modules.append(file_name)
    if lower_camel_case_modules:
        print ''
        print lower_camel_case_modules
        print 'Total lower camel case modules: %s' % len(lower_camel_case_modules)
    else:
        print 'No lower camel case modules found.'
    print ''


if __name__ == '__main__':
    iotools.clear_terminal()
    print 'Finding lower camel case modules ...'
    print ''
    _find_lower_camel_case_modules()
