#! /usr/bin/env python

from abjad.tools.mathtools import greatest_common_divisor
import os


def _remove_tmp_out_directories():
   total_file_names = 0
   bad_files, good_files = [ ], [ ]
   for dir_path, dir_names, file_names in os.walk('.'):
      for dir_name in dir_names:
         if dir_name == 'tmp_out':
            full_path = os.path.abspath(os.path.join(dir_path, dir_name))
            os.rmdir(full_path)
   print ''
   

if __name__ == '__main__':
   iotools.clear_terminal()
   _remove_tmp_out_directories()
