#! /usr/bin/env python

from abjad.tools import iotools


abjad_prompt = 'abjad' + '>'
python_prompt = 3 * '>'
command = "replace-in-files . ' %s ' ' %s ' false" % (abjad_prompt, python_prompt)
iotools.spawn_subprocess(command)
