#! /usr/bin/env python

from abjad.tools import iotools


python_prompt = 3 * '>'
abjad_prompt = 'abjad' + '>'
command = "replace-in-files . ' %s ' ' %s ' false" % (python_prompt, abjad_prompt)
iotools.spawn_subprocess(command)
