autodetect: false

doc-warnings: no

test-warnings: no

ignore-paths:
    - experimental

ignore-patterns:
    - (^|/)docs(/|$)

max-line-length: 80

requirements:
    - requirements.txt

strictness: veryhigh

pep8:
    full: true
    disable:
        - E123
        - E125
        - W292

pylint:
    disable:
        - W0232

pyroma:
    run: true
