autodetect: false

doc-warnings: no

test-warnings: no

ignore-paths:
    - experimental

ignore-patterns:
    - (^|/)docs(/|$)

max-line-length: 80

requirements:
    - requirements.txt

strictness: veryhigh

pep8:
    full: true
    disable:
        - E123 # closing bracket does not match indentation of opening bracket’s line
        - E124 # closing bracket does not match visual indentation
        - E125 # continuation line with same indent as next logical line
        - E128 # continuation line under-indented for visual indent
        - W292 # no newline at end of file

pylint:
    disable:
        - C0111 # Missing docstring
        - E1102 # Not callable
        - R0201 # Method could be a function
        - R0901 # Too many ancestors
        - R0903 # Too few public methods
        - R0904 # Too many public methods
        - W0142 # Used * or ** magic
        - W0212 # Access to a protected member %s of a client class
        - W0232 # Class has no __init__ method
        - W0613 # Unused argument
        - W0614 # Unused import from wildcard import

pyroma:
    run: true