# -*- encoding: utf-8 -*-
from abjad import *


def apply_dynamic_marks(score):

    voice = score['Bell Voice']
    dynamic = contexttools.DynamicMark('ppp')
    attach(dynamic, voice[0][1])
    dynamic = contexttools.DynamicMark('pp')
    attach(dynamic, voice[8][1])
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[18][1])
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[26][1])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[34][1])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[42][1])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[52][1])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[60][1])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[68][1])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[76][1])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[84][1])
    dynamic = contexttools.DynamicMark('pp')
    attach(dynamic, voice[-1][0])

    voice = score['First Violin Voice']
    dynamic = contexttools.DynamicMark('ppp')
    attach(dynamic, voice[6][1])
    dynamic = contexttools.DynamicMark('pp')
    attach(dynamic, voice[15][0])
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[22][3])
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[31][0])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[38][3])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[47][0])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[55][2])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[62][2])

    voice = score['Second Violin Voice']
    dynamic = contexttools.DynamicMark('pp')
    attach(dynamic, voice[7][0])
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[12][0])
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[16][0])
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[25][1])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[34][1])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[44][1])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[54][0])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[62][1])

    voice = score['Viola Voice']
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[8][0])
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[19][1])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[30][0])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[36][0])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[42][0])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[52][0])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[62][0])

    voice = score['Cello Voice']
    dynamic = contexttools.DynamicMark('p')
    attach(dynamic, voice[10][0])
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[21][0])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[31][0])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[43][0])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[52][1])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[62][0])

    voice = score['Bass Voice']
    dynamic = contexttools.DynamicMark('mp')
    attach(dynamic, voice[14][0])
    dynamic = contexttools.DynamicMark('mf')
    attach(dynamic, voice[27][0])
    dynamic = contexttools.DynamicMark('f')
    attach(dynamic, voice[39][0])
    dynamic = contexttools.DynamicMark('ff')
    attach(dynamic, voice[51][0])
    dynamic = contexttools.DynamicMark('fff')
    attach(dynamic, voice[62][0])
