current_module = {
    '$current-book': None,
    '$current-bookpart': None,
    '$defaultheader': None,
    '$defaultlayout': None,
    '$defaultmidi': None,
    '$defaultpaper': None,
    '%module-public-interface': None,
    'accent': {,
        'articulation-type': 'accent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'acciaccatura': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'add-toc-item!': None,
    'addChordShape': {
        'signature': ('symbol?', 'pair?', 'string-or-pair?',),
        'type': 'ly:music-function?',
    },
    'addInstrumentDefinition': {
        'signature': ('string?', 'list?',),
        'type': 'ly:music-function?',
    },
    'addQuote': {
        'signature': ('string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'aeolian': None,
    'afterGrace': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'afterGraceFraction': None,
    'aikenHeads': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'aikenHeadsMinor': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'allowPageTurn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'applyContext': {
        'signature': ('procedure?',),
        'type': 'ly:music-function?',
    },
    'applyMusic': {
        'signature': ('procedure?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'applyOutput': {
        'signature': ('symbol?', 'procedure?',),
        'type': 'ly:music-function?',
    },
    'appoggiatura': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'arpeggio': {,
        'name': 'ArpeggioEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'arpeggio-event', 'event',),
    },
    'arpeggioArrowDown': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioArrowUp': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioBracket': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioNormal': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioParenthesis': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioParenthesisDashed': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'assertBeamQuant': {
        'signature': ('pair?', 'pair?',),
        'type': 'ly:music-function?',
    },
    'assertBeamSlope': {
        'signature': ('procedure?',),
        'type': 'ly:music-function?',
    },
    'autoBeamOff': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'autoBeamOn': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'autochange': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'balloonGrobText': {
        'signature': ('symbol?', 'number-pair?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'balloonLengthOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'balloonLengthOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'balloonText': {
        'signature': ('number-pair?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'banjo-c-tuning': None,
    'banjo-modal-tuning': None,
    'banjo-open-d-tuning': None,
    'banjo-open-dm-tuning': None,
    'banjo-open-g-tuning': None,
    'bar': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'barNumberCheck': {
        'signature': ('integer?',),
        'type': 'ly:music-function?',
    },
    'baritone-ukulele-tuning': None,
    'bass-drop-d-tuning': None,
    'bass-five-string-tuning': None,
    'bass-four-string-tuning': None,
    'bass-six-string-tuning': None,
    'bass-tuning': None,
    'bassFigureExtendersOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'bassFigureExtendersOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'bassFigureStaffAlignmentDown': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bassFigureStaffAlignmentNeutral': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bassFigureStaffAlignmentUp': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bendAfter': {
        'signature': ('real?',),
        'type': 'ly:music-function?',
    },
    'bigger': 1,
    'blackTriangleMarkup': None,
    'bongos-style': None,
    'book-bookpart-handler': None,
    'book-filename': None,
    'book-music-handler': None,
    'book-output-suffix': None,
    'book-score-handler': None,
    'book-text-handler': None,
    'bookOutputName': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'bookOutputSuffix': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'bookpart-music-handler': None,
    'bookpart-score-handler': None,
    'bookpart-text-handler': None,
    'bracketCloseSymbol': {,
        'name': 'BeamEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'beam-event', 'span-event',),
    },
    'bracketOpenSymbol': {,
        'name': 'BeamEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'beam-event', 'span-event',),
    },
    'break': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'breakDynamicSpan': {,
        'name': 'BreakDynamicSpanEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'break-span-event', 'break-dynamic-span-event', 'event',),
    },
    'breathe': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'breve': None,
    'cadenzaOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'cadenzaOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'cello-tuning': None,
    'center': 0,
    'chord->tuning': None,
    'chord-shape': None,
    'chord-shape-table': None,
    'chordGlissando': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'chordmodifiers': None,
    'clef': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'coda': {,
        'articulation-type': 'coda',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'compoundMeter': {
        'signature': ('pair?',),
        'type': 'ly:music-function?',
    },
    'compressFullBarRests': {,
        'context-type': 'Score',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'congas-style': None,
    'contextStringTuning': {
        'signature': ('symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'cr': {,
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'cresc': {,
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'crescHairpin': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'crescTextCresc': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'cueClef': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'cueClefUnset': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'cueDuring': {
        'signature': ('string?', 'ly:dir?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'cueDuringWithClef': {
        'signature': ('string?', 'ly:dir?', 'string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'dashBar': {
        'alias': 'staccatissimo',
        'type': 'alias',
    },
    'dashDash': {
        'alias': 'tenuto',
        'type': 'alias',
    },
    'dashDot': {
        'alias': 'staccato',
        'type': 'alias',
    },
    'dashHat': {
        'alias': 'marcato',
        'type': 'alias',
    },
    'dashLarger': {
        'alias': 'accent',
        'type': 'alias',
    },
    'dashPlus': {
        'alias': 'stopped',
        'type': 'alias',
    },
    'dashUnderscore': {
        'alias': 'portato',
        'type': 'alias',
    },
    'deadNote': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'deadNotesOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deadNotesOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'decr': {,
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'decresc': {,
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'default-fret-table': None,
    'default-repeat-chord': None,
    'defaultNoteHeads': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'defaultStringTunings': None,
    'defaultTimeSignature': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'deprecatedcresc': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecateddim': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecatedendcresc': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecatedenddim': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dim': {,
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'dimHairpin': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDecr': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDecresc': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDim': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'displayLilyMusic': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'displayMusic': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'dorian': None,
    'dotsDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'dotsNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'dotsUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'double-bass-tuning': None,
    'down': -1,
    'downbow': {,
        'articulation-type': 'downbow',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'downmordent': {,
        'articulation-type': 'downmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'downprall': {,
        'articulation-type': 'downprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'drumPitchNames': None,
    'drums-style': None,
    'dynamicDown': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dynamicNeutral': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dynamicUp': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'easyHeadsOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'easyHeadsOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'endSpanners': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'endcr': {,
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'endcresc': {,
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'enddecr': {,
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'enddecresc': {,
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'enddim': {,
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'endincipit': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'episemFinis': {,
        'name': 'EpisemaEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'episema-event',),
    },
    'episemInitium': {,
        'name': 'EpisemaEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'episema-event',),
    },
    'escapedBiggerSymbol': {,
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'escapedExclamationSymbol': {,
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'escapedParenthesisCloseSymbol': {,
        'name': 'PhrasingSlurEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'phrasing-slur-event',),
    },
    'escapedParenthesisOpenSymbol': {,
        'name': 'PhrasingSlurEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'phrasing-slur-event',),
    },
    'escapedSmallerSymbol': {,
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'espressivo': {,
        'articulation-type': 'espressivo',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'expandFullBarRests': {,
        'context-type': 'Score',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'expect-error': None,
    'f': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'f',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'featherDurations': {
        'signature': ('ly:moment?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'fermata': {,
        'articulation-type': 'fermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'fermataMarkup': {,
        'name': 'MultiMeasureTextEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'multi-measure-text-event',),
    },
    'ff': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'ff',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'fff': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'fff',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ffff': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'ffff',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'fffff': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'fffff',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'flageolet': {,
        'articulation-type': 'flageolet',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'footnote': {
        'signature': ('number-pair?', 'cheap-markup?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'footnoteGrob': {
        'signature': ('symbol?', 'number-pair?', 'cheap-markup?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'four-string-banjo': None,
    'fp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'fp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'frenchChords': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'fullJazzExceptions': None,
    'funkHeads': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'funkHeadsMinor': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'fz': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'fz',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'germanChords': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'glissando': {,
        'name': 'GlissandoEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'glissando-event', 'event',),
    },
    'grace': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'guitar-asus4-tuning': None,
    'guitar-dadgad-tuning': None,
    'guitar-drop-d-tuning': None,
    'guitar-lute-tuning': None,
    'guitar-open-d-tuning': None,
    'guitar-open-g-tuning': None,
    'guitar-seven-string-tuning': None,
    'guitar-tuning': None,
    'halfopen': {,
        'articulation-type': 'halfopen',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'harmonic': {,
        'name': 'HarmonicEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'harmonic-event',),
    },
    'harmonicByFret': {
        'signature': ('number?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicByRatio': {
        'signature': ('number?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicNote': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicsOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'harmonicsOn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'hideNotes': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'hideSplitTiedTabNotes': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'hideStaffSwitch': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'huge': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'ignatzekExceptionMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'ignatzekExceptions': None,
    'improvisationOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'improvisationOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'input-file-name': None,
    'instrument-definitions': None,
    'instrumentSwitch': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'inversion': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'ionian': None,
    'italianChords': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'keepWithTag': {
        'signature': ('symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'killCues': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'label': {
        'signature': ('symbol?',),
        'type': 'ly:music-function?',
    },
    'laissezVibrer': {,
        'name': 'LaissezVibrerEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'laissez-vibrer-event',),
    },
    'language': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'languageRestore': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'languageSaveAndChange': {
        'signature': ('string?',),
        'type': 'ly:music-function?',
    },
    'large': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'left': -1,
    'lheel': {,
        'articulation-type': 'lheel',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'lineprall': {,
        'articulation-type': 'lineprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'locrian': None,
    'longa': None,
    'longfermata': {,
        'articulation-type': 'longfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'ltoe': {,
        'articulation-type': 'ltoe',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'lydian': None,
    'major': None,
    'make-dynamic-script': None,
    'make-fretboard-table': None,
    'make-repeat-chord-function': None,
    'make-simple-dash-definition': None,
    'make-table-of-contents-markup-list': None,
    'makeClusters': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'makeDefaultStringTunings': {
        'signature': ('cheap-list?',),
        'type': 'ly:music-function?',
    },
    'makeStringTuning': {
        'signature': ('symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'mandolin-tuning': None,
    'marcato': {,
        'articulation-type': 'marcato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'maxima': None,
    'melisma': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'melismaEnd': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyDottedOff': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyDottedOn': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyHeadedOff': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyHeadedOn': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mf': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'mf',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'midiDrumPitches': None,
    'minor': None,
    'mixolydian': None,
    'modalInversion': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'modalTranspose': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'mordent': {,
        'articulation-type': 'mordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'mp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'mp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'musicMap': {
        'signature': ('procedure?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'musicQuotes': None,
    'newSpacingSection': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'noBeam': {,
        'name': 'BeamForbidEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'beam-forbid-event',),
    },
    'noBreak': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'noPageBreak': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'noPageTurn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'normalsize': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'numericTimeSignature': {,
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'octaveCheck': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'oneVoice': {,
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'open': {,
        'articulation-type': 'open',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'ottava': {
        'signature': ('integer?',),
        'type': 'ly:music-function?',
    },
    'output-empty-score-list': None,
    'output-suffix': None,
    'overrideProperty': {
        'signature': ('string?', 'symbol?', 'scheme?',),
        'type': 'ly:music-function?',
    },
    'overrideTimeSignatureSettings': {
        'signature': ('pair?', 'pair?', 'cheap-list?', 'cheap-list?',),
        'type': 'ly:music-function?',
    },
    'p': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'p',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'pageBreak': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'pageTurn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'palmMute': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'palmMuteOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'palmMuteOn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'parallelMusic': {
        'signature': ('list?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'parenthesisCloseSymbol': {,
        'name': 'SlurEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'slur-event',),
    },
    'parenthesisOpenSymbol': {,
        'name': 'SlurEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'slur-event',),
    },
    'parenthesize': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'parser': None,
    'partCombineListener': None,
    'partcombine': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'partcombineApart': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineApartOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineAutomatic': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineAutomaticOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineChords': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineChordsOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineForce': {
        'signature': ('symbol-or-boolean?', 'boolean?',),
        'type': 'ly:music-function?',
    },
    'partcombineSoloI': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloII': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloIIOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloIOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineUnisono': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineUnisonoOnce': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partialJazzExceptions': None,
    'partialJazzMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'percussion-style': None,
    'phrasingSlurDashPattern': {
        'signature': ('number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'phrasingSlurDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurDotted': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurHalfDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurHalfSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrygian': None,
    'pipeSymbol': {,
        'name': 'BarCheck',
        'type': 'ly:prob?',
        'types': ('general-music', 'bar-check',),
    },
    'pitchedTrill': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'pointAndClickOff': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'pointAndClickOn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'portato': {,
        'articulation-type': 'portato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'powerChordExceptions': None,
    'powerChordSymbol': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'powerChords': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'pp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'pp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ppp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'ppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'pppp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'pppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ppppp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'ppppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'prall': {,
        'articulation-type': 'prall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'pralldown': {,
        'articulation-type': 'pralldown',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'prallmordent': {,
        'articulation-type': 'prallmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'prallprall': {,
        'articulation-type': 'prallprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'prallup': {,
        'articulation-type': 'prallup',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'predefinedFretboardsOff': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'predefinedFretboardsOn': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'quoteDuring': {
        'signature': ('string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'removeWithTag': {
        'signature': ('symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'repeatTie': {,
        'name': 'RepeatTieEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'repeat-tie-event',),
    },
    'resetRelativeOctave': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'retrograde': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'reverseturn': {,
        'articulation-type': 'reverseturn',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'revertTimeSignatureSettings': {
        'signature': ('pair?',),
        'type': 'ly:music-function?',
    },
    'rfz': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'rfz',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'rheel': {,
        'articulation-type': 'rheel',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'right': 1,
    'rightHandFinger': {
        'signature': ('number-or-string?',),
        'type': 'ly:music-function?',
    },
    'rtoe': {,
        'articulation-type': 'rtoe',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'sacredHarpHeads': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'sacredHarpHeadsMinor': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'scaleDurations': {
        'signature': ('number-pair?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'segno': {,
        'articulation-type': 'segno',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'semiGermanChords': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'setDefaultDurationToQuarter': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'sf': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'sf',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sff': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'sff',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sfp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'sfp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sfz': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'sfz',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'shiftDurations': {
        'signature': ('integer?', 'integer?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'shiftOff': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOn': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOnn': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOnnn': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shortfermata': {,
        'articulation-type': 'shortfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'showSplitTiedTabNotes': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'showStaffSwitch': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'signumcongruentiae': {,
        'articulation-type': 'signumcongruentiae',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'slurDashPattern': {
        'signature': ('number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'slurDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurDotted': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurHalfDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurHalfSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'small': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'smaller': -1,
    'snappizzicato': {,
        'articulation-type': 'snappizzicato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'sostenutoOff': {,
        'name': 'SostenutoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'sostenuto-event',),
    },
    'sostenutoOn': {,
        'name': 'SostenutoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'sostenuto-event',),
    },
    'southernHarmonyHeads': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'southernHarmonyHeadsMinor': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'sp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'sp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'spacingTweaks': {
        'signature': ('list?',),
        'type': 'ly:music-function?',
    },
    'spp': {,
        'name': 'AbsoluteDynamicEvent',
        'text': 'spp',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'staccatissimo': {,
        'articulation-type': 'staccatissimo',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'staccato': {,
        'articulation-type': 'staccato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'start': -1,
    'startAcciaccaturaMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startAppoggiaturaMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startGraceMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startGroup': {,
        'name': 'NoteGroupingEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'note-grouping-event',),
    },
    'startStaff': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'startTextSpan': {,
        'name': 'TextSpanEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'text-span-event',),
    },
    'startTrillSpan': {,
        'name': 'TrillSpanEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'trill-span-event',),
    },
    'stemDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stemNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stemUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stop': 1,
    'stopAcciaccaturaMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopAppoggiaturaMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopGraceMusic': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopGroup': {,
        'name': 'NoteGroupingEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'note-grouping-event',),
    },
    'stopStaff': {,
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'stopTextSpan': {,
        'name': 'TextSpanEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'text-span-event',),
    },
    'stopTrillSpan': {,
        'name': 'TrillSpanEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'span-event', 'event', 'trill-span-event',),
    },
    'stopped': {,
        'articulation-type': 'stopped',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'storePredefinedDiagram': {
        'signature': ('hash-table?', 'ly:music?', 'pair?', 'string-or-pair?',),
        'type': 'ly:music-function?',
    },
    'styledNoteHeads': {
        'signature': ('symbol?', 'list-or-symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'sustainOff': {,
        'name': 'SustainEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'sustain-event',),
    },
    'sustainOn': {,
        'name': 'SustainEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'sustain-event',),
    },
    'tab-repeat-chord': None,
    'tabChordRepetition': {
        'signature': None,
        'type': 'ly:music-function?',
    },
    'tabFullNotation': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'table-of-contents-markup-list': None,
    'tag': {
        'signature': ('symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'teeny': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tenor-ukulele-tuning': None,
    'tenuto': {,
        'articulation-type': 'tenuto',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'textLengthOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'textLengthOn': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'textSpannerDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'textSpannerNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'textSpannerUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'thumb': {,
        'articulation-type': 'thumb',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'tieDashPattern': {
        'signature': ('number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'tieDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieDotted': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieHalfDashed': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieHalfSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieSolid': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tildeSymbol': {,
        'name': 'TieEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'tie-event', 'event',),
    },
    'timbales-style': None,
    'tiny': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'toc-items': None,
    'tocItem': {
        'signature': ('cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'tocItemWithDotsMarkup': None,
    'toplevel-book-handler': None,
    'toplevel-bookpart-handler': None,
    'toplevel-bookparts': None,
    'toplevel-music-handler': None,
    'toplevel-score-handler': None,
    'toplevel-scores': None,
    'toplevel-text-handler': None,
    'transposedCueDuring': {
        'signature': ('string?', 'ly:dir?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'transposition': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'treCorde': {,
        'name': 'UnaCordaEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'una-corda-event',),
    },
    'trill': {,
        'articulation-type': 'trill',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'tupletDown': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tupletNeutral': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tupletUp': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'turn': {,
        'articulation-type': 'turn',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'tweak': {
        'signature': ('symbol?', 'scheme?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'ukulele-d-tuning': None,
    'ukulele-tuning': None,
    'unHideNotes': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'unaCorda': {,
        'name': 'UnaCordaEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'pedal-event', 'una-corda-event',),
    },
    'unfoldRepeats': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'up': 1,
    'upbow': {,
        'articulation-type': 'upbow',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'upmordent': {,
        'articulation-type': 'upmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'upprall': {,
        'articulation-type': 'upprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'varcoda': {,
        'articulation-type': 'varcoda',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'version-seen': None,
    'verylongfermata': {,
        'articulation-type': 'verylongfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'articulation-event', 'script-event',),
    },
    'viola-tuning': None,
    'violin-tuning': None,
    'voiceFour': {,
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceFourStyle': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceNeutralStyle': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceOne': {,
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceOneStyle': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceThree': {,
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceThreeStyle': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceTwo': {,
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceTwoStyle': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'walkerHeads': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'walkerHeadsMinor': {,
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'whiteTriangleMarkup': None,
    'withMusicProperty': {
        'signature': ('symbol?', 'scheme?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'xNote': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'xNotesOff': {,
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'xNotesOn': {
        'signature': None,
        'type': 'ly:music-function?',
    },
}