from .Instrument import Instrument
from .Accordion import Accordion
from .AltoFlute import AltoFlute
from .AltoSaxophone import AltoSaxophone
from .AltoTrombone import AltoTrombone
from .AltoVoice import AltoVoice
from .BaritoneSaxophone import BaritoneSaxophone
from .BaritoneVoice import BaritoneVoice
from .BassClarinet import BassClarinet
from .BassFlute import BassFlute
from .BassSaxophone import BassSaxophone
from .BassTrombone import BassTrombone
from .BassVoice import BassVoice
from .Bassoon import Bassoon
from .Cello import Cello
from .ClarinetInA import ClarinetInA
from .ClarinetInBFlat import ClarinetInBFlat
from .ClarinetInEFlat import ClarinetInEFlat
from .Contrabass import Contrabass
from .ContrabassClarinet import ContrabassClarinet
from .ContrabassFlute import ContrabassFlute
from .ContrabassSaxophone import ContrabassSaxophone
from .Contrabassoon import Contrabassoon
from .EnglishHorn import EnglishHorn
from .Flute import Flute
from .FrenchHorn import FrenchHorn
from .Glockenspiel import Glockenspiel
from .Guitar import Guitar
from .Harp import Harp
from .Harpsichord import Harpsichord
from .InstrumentDictionary import InstrumentDictionary
from .Marimba import Marimba
from .MezzoSopranoVoice import MezzoSopranoVoice
from .Oboe import Oboe
from .Percussion import Percussion
from .Piano import Piano
from .Piccolo import Piccolo
from .SopraninoSaxophone import SopraninoSaxophone
from .SopranoSaxophone import SopranoSaxophone
from .SopranoVoice import SopranoVoice
from .TenorSaxophone import TenorSaxophone
from .TenorTrombone import TenorTrombone
from .TenorVoice import TenorVoice
from .Trumpet import Trumpet
from .Tuba import Tuba
from .Vibraphone import Vibraphone
from .Viola import Viola
from .Violin import Violin
from .Xylophone import Xylophone

_documentation_section = 'core'
