from abjad.components._Component._ComponentSpannerAggregator import _ComponentSpannerAggregator


class _LeafSpannerAggregator(_ComponentSpannerAggregator):

   @property
   def _after(self):
      from abjad.tools.leaftools._get_after_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf import _get_after_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf
      return _get_after_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf(self)

   @property
   def _before(self):
      from abjad.tools.leaftools._get_before_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf import _get_before_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf
      return _get_before_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf(self)

   @property
   def _left(self):
      from abjad.tools.leaftools._get_left_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf import _get_left_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf
      return _get_left_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf(self)

   @property
   def _right(self):
      from abjad.tools.leaftools._get_right_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf import _get_right_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf
      return _get_right_slot_format_contributions_from_spanners_attached_to_any_improper_parent_of_leaf(self)
