#! /usr/bin/env python
import abjad
import sys
import time


abjad.IOManager.clear_terminal()
start_time = time.time()
argument = sys.argv[1]
command = r'ack'
command += r' --ignore-dir=build'
command += r' --ignore-dir=_docs'
command += r' --ignore-dir=docs'
command += r' --ignore-file=ext:eps'
command += r' --ignore-file=is:.coverage'
if "'" in argument:
    command += r' "{}"'
else:
    command += r" '{}'"
command = command.format(argument)
print('abjad-ack is running this command:')
print()
print('    ' + command)
print()

abjad.IOManager.spawn_subprocess(command)
stop_time = time.time()
total_time = stop_time - start_time

print()
print('abjad-ack total time: {} second(s).'.format(int(total_time)))
print()
