#! /usr/bin/env python


if __name__ == '__main__':
    import sys
    from abjad.tools import developerscripttools
    script = developerscripttools.RunDoctestsScript()
    args = sys.argv[1:]
    script(args)
