#!/usr/bin/env python
import abjad
import os


if __name__ == '__main__':
    abjad.documentationtools.AbjadAPIGenerator()(verbose=True)
    print 'Now building the HTML docs ...'
    print ''
    docs_directory = os.path.join(
        abjad.abjad_configuration.abjad_directory,
        'docs',
        )
    os.chdir(docs_directory)
    abjad.IOManager.spawn_subprocess('make html')
