#! /usr/bin/env python
import sys
import scoremanager


score_manager = scoremanager.core.ScoreManager(is_test=False)
input_ = ' '.join(sys.argv[1:]) 
score_manager._run(
    write_transcript=True,
    pending_user_input=input_,
    display_active_scores=True,
    )
