#! /usr/bin/env python
import sys
import scoremanager


score_manager = scoremanager.core.ScoreManager()
score_manager._run(
    dump_transcript=True,
    pending_user_input=' '.join(sys.argv[1:]), 
    show_example_scores=False,
    )
