from .make_desordre_cell import make_desordre_cell
from .make_desordre_lilypond_file import make_desordre_lilypond_file
from .make_desordre_measure import make_desordre_measure
from .make_desordre_pitches import make_desordre_pitches
from .make_desordre_score import make_desordre_score
from .make_desordre_staff import make_desordre_staff

_documentation_section = 'demos'
