from abjad.tools.pitchtools import set_ascending_named_chromatic_pitches_on_nontied_pitched_components_in_expr as chromaticize
from abjad.tools.pitchtools import set_ascending_named_diatonic_pitches_on_nontied_pitched_components_in_expr as diatonicize
