from .PartCantusScoreTemplate import PartCantusScoreTemplate
from .add_bell_music_to_score import add_bell_music_to_score
from .add_string_music_to_score import add_string_music_to_score
from .apply_bowing_marks import apply_bowing_marks
from .apply_dynamics import apply_dynamics
from .apply_expressive_marks import apply_expressive_marks
from .apply_final_bar_lines import apply_final_bar_lines
from .apply_page_breaks import apply_page_breaks
from .apply_rehearsal_marks import apply_rehearsal_marks
from .configure_lilypond_file import configure_lilypond_file
from .configure_score import configure_score
from .create_pitch_contour_reservoir import create_pitch_contour_reservoir
from .durate_pitch_contour_reservoir import durate_pitch_contour_reservoir
from .edit_bass_voice import edit_bass_voice
from .edit_cello_voice import edit_cello_voice
from .edit_first_violin_voice import edit_first_violin_voice
from .edit_second_violin_voice import edit_second_violin_voice
from .edit_viola_voice import edit_viola_voice
from .make_part_lilypond_file import make_part_lilypond_file
from .shadow_pitch_contour_reservoir import shadow_pitch_contour_reservoir

_documentation_section = 'demos'
