#! /usr/bin/env python

import os
from abjad.cfg._remove_abjad_pyc_files import _remove_abjad_pyc_files


_remove_abjad_pyc_files( )

## OS-portable version of something like ...
##
##    find . -name '*.pyc' -exec rm {} \; 
##
## ... that uses Python instead.
