#! /usr/bin/env python

import sys
import time
from abjad.tools import iotools


iotools.clear_terminal()
start_time = time.time()
command = r'ack --ignore-dir=docs --ignore-dir=build {!r}'
command = command.format(sys.argv[1])
print 'abjad-ack is running this command:'
print
print '    ' + command
print

iotools.IOManager.spawn_subprocess(command)
stop_time = time.time()
total_time = stop_time - start_time

print
print 'abjad-ack total time: {} second(s).'.format(int(total_time))
print
