#! /usr/bin/env python

from abjad import abjad_configuration
from abjad.tools import systemtools
from abjad.tools.systemtools.update_docs_release_string import update_docs_release_string
import os


# find start directory and project root
start_directory = os.path.abspath('.')
project_root = abjad_configuration.abjad_directory_path.rstrip('abjad')

# svn update
os.chdir(project_root)
systemtools.IOManager.clear_terminal()
systemtools.IOManager.spawn_subprocess('svn update')
os.chdir(start_directory)

# remove Abjad *.pyc files, __pycache__ directories and tmp* files
systemtools.IOManager.spawn_subprocess('ajv clean {}'.format(project_root))
