#! /usr/bin/env python
import os
from abjad import abjad_configuration
from abjad.tools import systemtools


def list_private_modules():
    tools_path = os.path.join(
        abjad_configuration.abjad_directory,
        'tools',
        )
    private_module_names = []
    for directory, subdirectory_names, file_names in os.walk(tools_path):
        for file_name in file_names:
            if file_name.endswith('.py'):
                if not file_name == '__init__.py':
                    if file_name.startswith('_'):
                        if file_name[1].islower():
                            full_name = os.path.join(
                                directory,
                                file_name,
                                )
                            private_module_names.append(full_name)
    total_private = len(private_module_names)
    for x in private_module_names:
        print(x)
    print()
    print('Total private module names: {}'.format(total_private))
    print()


if __name__ == '__main__':
    systemtools.IOManager.clear_terminal()
    list_private_modules()
