#! /usr/bin/env python

import os

def find_filenames_with_forbidden_characters():
   forbidden_characters = (' ', )
   for dirpath, dirnames, filenames in os.walk('.'):
      for filename in filenames:
         if 'svn' not in dirpath and 'svn' not in filename:
            for forbidden_character in forbidden_characters:
               if forbidden_character in filename:
                  full_filename = os.path.join(dirpath, filename)
                  print full_filename


if __name__ == '__main__':
   os.system('clear')
   find_filenames_with_forbidden_characters()
   print ''
