#! /usr/bin/env python

import os
import sys


ABJADPATH = os.environ.get('ABJADPATH')
start_directory = os.path.abspath('.')
os.chdir(ABJADPATH)
os.system('clear')
os.system('grep -Irn "%s" * | grep -v svn | grep -v documentation' % 
   sys.argv[1])
os.chdir(start_directory)
