#! /usr/bin/env python
import os
from abjad.cfg.cfg import ABJADPATH
from abjad.cfg.abjad_version import _write_abjad_versionfile


start_directory = os.path.abspath('.')
project_root = ABJADPATH.rstrip('abjad')

## svn update
os.chdir(project_root)
os.system('clear')
os.system('svn update')
os.chdir(start_directory)

## write version file
#_write_abjad_versionfile( )

## remove *.pyc files
for root, dirs, files in os.walk(project_root):
   if '.svn' in dirs:
      dirs.remove('.svn')
   for file in files:
      if file.endswith('.pyc'):
         file_full_path = os.path.join(root, file)
         os.remove(file_full_path)

