#!/usr/bin/env python

import os
from abjad.tools import iotools
from abjad.tools.documentationtools import AbjadAPIGenerator


if __name__ == '__main__':
    from abjad import ABJCFG

    AbjadAPIGenerator()(verbose=True)

    # print greeting
    print 'Now building the HTML docs ...'
    print ''

    # change to docs directory because makefile lives there
    docs_directory = os.path.join(ABJCFG.ABJAD_PATH, 'docs')
    os.chdir(docs_directory)

    # make html docs
    iotools.spawn_subprocess('make html')
