#! /usr/bin/env python
import sys
import time

abjad.IOManager.spawn_subprocess("clear")
start_time = time.time()
argument = sys.argv[1]
if "'" in argument:
    command = r'ack --ignore-dir=docs --ignore-dir=build "{}"'
else:
    command = r"ack --ignore-dir=docs --ignore-dir=build '{}'"
command = command.format(argument)
print 'abjad-ack is running this command:'
print
print '    ' + command
print

abjad.IOManager.spawn_subprocess(command)
stop_time = time.time()
total_time = stop_time - start_time

print
print 'abjad-ack total time: {} second(s).'.format(int(total_time))
print
