#! /usr/bin/env python
import pathlib
import sys

import abjad

if __name__ == "__main__":

    try:
        file_name = sys.argv[1]
    except IndexError:
        file_name = ""

    namespace = {}
    configuration = abjad.Configuration()
    path = configuration.abjad_directory / "abjad" / "_version.py"
    with open(path) as pointer:
        lines = pointer.readlines()
        string = "".join(lines)
        exec(string, namespace)
    version_string = namespace["__version__"]
    startup_string = f"Abjad {version_string} (development)"

    commands = " ".join(
        [
            "import abjad;",
            f"print({startup_string!r});",
        ]
    )

    string = rf'''python -i {file_name} -c "{commands}"'''
    abjad.iox.spawn_subprocess(string)
