#! /usr/bin/env python
import abjad
import sys
import time


abjad.IOManager.clear_terminal()
start_time = time.time()
argument = sys.argv[1]

command = "ack --type-set defpy:match:/definition.py/ --defpy --sort-files"
if "'" in argument:
    command += r' "{}"'
else:
    command += r" '{}'"
command = command.format(argument)
print("abjad-ack is running this command:")
print()
print("    " + command)
print()

abjad.IOManager.spawn_subprocess(command)
stop_time = time.time()
total_time = int(stop_time - start_time)

print()
counter = abjad.String.pluralize("second", total_time)
print(f"abjad-ack total time {total_time} {counter}.")
print()
