#! /usr/bin/env python
import sys
import time

import abjad

abjad.IOManager.clear_terminal()
start_time = time.time()
argument = sys.argv[1]
command = r"ack"
command += r" --ignore-dir=.mypy_cache"
command += r" --ignore-dir=_docs"
command += r" --ignore-dir=build"
command += r" --ignore-dir=docs"
command += r" --python"
command += r" --sort-files"
if "'" in argument:
    command += r' "{}"'
else:
    command += r" '{}'"
command = command.format(argument)
print("abjad-ack is running this command:")
print()
print("    " + command)
print()

abjad.IOManager.spawn_subprocess(command)
stop_time = time.time()
total_time = int(stop_time - start_time)

print()
counter = abjad.String.pluralize("second", total_time)
print(f"abjad-ack total time {total_time} {counter}.")
print()
