### DOCUMENT COMMANDS ###

SPACING_COMMAND = "SPACING_COMMAND"
SPACING_OVERRIDE_COMMAND = "SPACING_OVERRIDE_COMMAND"

### DOCUMENT MARKUP ###

CLOCK_TIME = "CLOCK_TIME"
FIGURE_NAME = "FIGURE_NAME"
LOCAL_MEASURE_NUMBER = "LOCAL_MEASURE_NUMBER"
MEASURE_NUMBER = "MEASURE_NUMBER"
SPACING = "SPACING"
SPACING_OVERRIDE = "SPACING_OVERRIDE"
STAGE_NUMBER = "STAGE_NUMBER"

### PITCH MANAGEMENT ###

ALLOW_OUT_OF_RANGE = "ALLOW_OUT_OF_RANGE"

STAFF_POSITION = "STAFF_POSITION"

### STRING CONSTANTS ###

HIDDEN = "HIDDEN"

REMOVE_ALL_EMPTY_STAVES = "REMOVE_ALL_EMPTY_STAVES"

TEMPORARY_CONTAINER = "TEMPORARY_CONTAINER"
