% SCORE_TITLE FORCES_TAGLINE 

% LILYPOND_VERSION_DIRECTIVE
% LILYPOND_LANGUAGE_DIRECTIVE

#(ly:set-option 'relative-includes #t)
% STYLESHEET_INCLUDE_STATEMENT

\score {
    {
%%% SEGMENTS %%%
    }
}