#!/usr/bin/env python

from make_sphinx_tocs import make_sphinx_tocs

if __name__ == '__main__':
   make_sphinx_tocs( )
   print ''
   print '... Done.'
   print ''
   print "You are now ready to build the HTML docs with 'make html'."
   print ''
