def _append_class_options(result):
#   result += '   :show-inheritance:\n'
    result += '   :members:\n'
    result += '   :undoc-members:\n'
    result += '   :inherited-members:\n'
    result += '   :special-members:\n'
    result += '   :exclude-members:\n'
    result += '       __abstractmethods__,\n'
    result += '       __class__,\n'
    result += '       __copy__,\n'
    result += '       __deepcopy__,\n'
    result += '       __dict__,\n'
    result += '       __format__,\n'
    result += '       __getnewargs__,\n'
    result += '       __init__,\n'
    result += '       __metaclass__,\n'
    result += '       __module__,\n'
    result += '       __new__,\n'
    result += '       __reduce__,\n'
    result += '       __reduce_ex__,\n'
    result += '       __sizeof__,\n'
    result += '       __slots__,\n'
    result += '       __subclasshook__,\n'
    result += '       __weakref__,\n'
    return result
