#!/usr/bin/env python

from abjad.tools.documentationtools import AbjadAPIGenerator
from make_html_docs import make_html_docs


if __name__ == '__main__':
    AbjadAPIGenerator()(verbose=True)
    make_html_docs()
