#!/usr/bin/env python

from make_sphinx_tocs import make_sphinx_tocs
from make_html_docs import make_html_docs


if __name__ == '__main__':
   make_sphinx_tocs(interactive = False)
   make_html_docs()
