language: python

python:
    - 2.7
    - 3.4

before_install:
    - wget -q http://download.linuxaudio.org/lilypond/binaries/linux-64/lilypond-2.19.29-1.linux-64.sh
    - sudo sh lilypond-2.19.29-1.linux-64.sh --batch
    - pip install --upgrade pip

install:
    - pip install --allow-external abjad --allow-unverified abjad -e git://github.com/Abjad/abjad.git#egg=abjad
    - pip install --allow-external ide --allow-unverified ide -e git://github.com/Abjad/ide.git#egg=ide
    #- pip install --allow-external {composer_library_package_name} --allow-unverified {composer_library_package_name} -e git://github.com/{composer_github_username}/{composer_library_package_name}.git#egg={composer_library_package_name}
    - pip install -e .

script:
    - ajv doctest -x ./{score_package_name}
    - py.test -xrf ./{score_package_name}
    - python ./{score_package_name}/test/test_segments.py

notifications:
    email: false