lilypond_version = "2.19.24"

contexts = {
    "ChoirStaff": {
        "accepts": set([
            "Staff",
            "StaffGroup",
            "RhythmicStaff",
            "PianoStaff",
            "Lyrics",
            "GrandStaff",
            "FiguredBass",
            "DrumStaff",
            "ChordNames",
            "ChoirStaff",
        ]),
        "aliases": set([]),
        "consists": set([
            "System_start_delimiter_engraver",
            "Instrument_name_engraver",
            "Vertical_align_engraver",
        ]),
        "default_child": "Staff",
    },
    "ChordNames": {
        "accepts": set([]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Axis_group_engraver",
            "Chord_name_engraver",
            "Separating_line_group_engraver",
            "Output_property_engraver",
        ]),
    },
    "CueVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Ligature_bracket_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "Devnull": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
            "Staff",
        ]),
        "consists": set([]),
    },
    "DrumStaff": {
        "accepts": set([
            "DrumVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Clef_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "DrumVoice",
    },
    "DrumVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Drum_notes_engraver",
            "Grob_pq_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Breathing_sign_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "Dynamics": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Axis_group_engraver",
            "Font_size_engraver",
            "Text_spanner_engraver",
            "Text_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Script_engraver",
            "Piano_pedal_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
    },
    "FiguredBass": {
        "accepts": set([]),
        "aliases": set([]),
        "consists": set([
            "Axis_group_engraver",
            "Separating_line_group_engraver",
            "Figured_bass_engraver",
        ]),
    },
    "FretBoards": {
        "accepts": set([]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Instrument_name_engraver",
            "Font_size_engraver",
            "Separating_line_group_engraver",
            "Axis_group_engraver",
            "Output_property_engraver",
            "Fretboard_engraver",
        ]),
    },
    "Global": {
        "accepts": set([
            "Score",
        ]),
        "aliases": set([]),
        "consists": set([]),
        "default_child": "Score",
    },
    "GrandStaff": {
        "accepts": set([
            "Staff",
            "TabStaff",
            "RhythmicStaff",
            "Lyrics",
            "FiguredBass",
            "Dynamics",
            "DrumStaff",
            "ChordNames",
        ]),
        "aliases": set([]),
        "consists": set([
            "Vertical_align_engraver",
            "System_start_delimiter_engraver",
            "Span_arpeggio_engraver",
            "Span_bar_stub_engraver",
            "Span_bar_engraver",
            "Instrument_name_engraver",
        ]),
        "default_child": "Staff",
    },
    "GregorianTranscriptionStaff": {
        "accepts": set([
            "GregorianTranscriptionVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "GregorianTranscriptionVoice",
    },
    "GregorianTranscriptionVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Episema_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Ligature_bracket_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "KievanStaff": {
        "accepts": set([
            "KievanVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "KievanVoice",
    },
    "KievanVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Kievan_ligature_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "Lyrics": {
        "accepts": set([]),
        "aliases": set([]),
        "consists": set([
            "Pure_from_neighbor_engraver",
            "Axis_group_engraver",
            "Font_size_engraver",
            "Instrument_name_engraver",
            "Stanza_number_engraver",
            "Hyphen_engraver",
            "Extender_engraver",
            "Lyric_engraver",
        ]),
    },
    "MensuralStaff": {
        "accepts": set([
            "MensuralVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Custos_engraver",
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "MensuralVoice",
    },
    "MensuralVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Mensural_ligature_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "NoteNames": {
        "accepts": set([]),
        "aliases": set([]),
        "consists": set([
            "Separating_line_group_engraver",
            "Note_name_engraver",
            "Tie_engraver",
            "Axis_group_engraver",
        ]),
    },
    "NullVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
            "Staff",
        ]),
        "consists": set([
            "Slur_engraver",
            "Beam_engraver",
            "Tie_engraver",
            "Grob_pq_engraver",
            "Pitch_squash_engraver",
            "Note_heads_engraver",
        ]),
    },
    "PetrucciStaff": {
        "accepts": set([
            "PetrucciVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Custos_engraver",
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "PetrucciVoice",
    },
    "PetrucciVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Mensural_ligature_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "PianoStaff": {
        "accepts": set([
            "Staff",
            "TabStaff",
            "RhythmicStaff",
            "Lyrics",
            "FiguredBass",
            "Dynamics",
            "DrumStaff",
            "ChordNames",
        ]),
        "aliases": set([
            "GrandStaff",
        ]),
        "consists": set([
            "Keep_alive_together_engraver",
            "Vertical_align_engraver",
            "Vertical_align_engraver",
            "System_start_delimiter_engraver",
            "Span_arpeggio_engraver",
            "Span_bar_stub_engraver",
            "Span_bar_engraver",
            "Instrument_name_engraver",
        ]),
        "default_child": "Staff",
    },
    "RhythmicStaff": {
        "accepts": set([
            "Voice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Ledger_line_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Time_signature_engraver",
            "Pitch_squash_engraver",
            "Staff_symbol_engraver",
            "Bar_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "Voice",
    },
    "Score": {
        "accepts": set([
            "Staff",
            "VaticanaStaff",
            "TabStaff",
            "StaffGroup",
            "RhythmicStaff",
            "PianoStaff",
            "PetrucciStaff",
            "NoteNames",
            "MensuralStaff",
            "Lyrics",
            "KievanStaff",
            "GregorianTranscriptionStaff",
            "GrandStaff",
            "FretBoards",
            "FiguredBass",
            "DrumStaff",
            "Devnull",
            "ChordNames",
            "ChoirStaff",
        ]),
        "aliases": set([
            "Timing",
        ]),
        "consists": set([
            "Footnote_engraver",
            "Beam_collision_engraver",
            "Concurrent_hairpin_engraver",
            "Parenthesis_engraver",
            "Bar_number_engraver",
            "Stanza_number_align_engraver",
            "Vertical_align_engraver",
            "Grace_spacing_engraver",
            "Spacing_engraver",
            "Break_align_engraver",
            "Metronome_mark_engraver",
            "Volta_engraver",
            "Mark_engraver",
            "System_start_delimiter_engraver",
            "Tweak_engraver",
            "Output_property_engraver",
            "Default_bar_line_engraver",
            "Timing_translator",
            "Staff_collecting_engraver",
            "Repeat_acknowledge_engraver",
            "Paper_column_engraver",
        ]),
        "default_child": "Staff",
    },
    "Staff": {
        "accepts": set([
            "Voice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([]),
        "consists": set([
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "Voice",
    },
    "StaffGroup": {
        "accepts": set([
            "Staff",
            "TabStaff",
            "StaffGroup",
            "RhythmicStaff",
            "PianoStaff",
            "Lyrics",
            "GrandStaff",
            "FretBoards",
            "FiguredBass",
            "DrumStaff",
            "ChordNames",
            "ChoirStaff",
        ]),
        "aliases": set([]),
        "consists": set([
            "System_start_delimiter_engraver",
            "Output_property_engraver",
            "Span_arpeggio_engraver",
            "Span_bar_stub_engraver",
            "Span_bar_engraver",
            "Instrument_name_engraver",
            "Vertical_align_engraver",
        ]),
        "default_child": "Staff",
    },
    "TabStaff": {
        "accepts": set([
            "TabVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Tab_staff_symbol_engraver",
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Time_signature_engraver",
            "Clef_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "TabVoice",
    },
    "TabVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Tab_tie_follow_engraver",
            "Tab_note_heads_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Breathing_sign_engraver",
            "Ligature_bracket_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "VaticanaStaff": {
        "accepts": set([
            "VaticanaVoice",
            "NullVoice",
            "CueVoice",
        ]),
        "aliases": set([
            "Staff",
        ]),
        "consists": set([
            "Custos_engraver",
            "Fingering_column_engraver",
            "Cue_clef_engraver",
            "Script_row_engraver",
            "Figured_bass_position_engraver",
            "Figured_bass_engraver",
            "Axis_group_engraver",
            "Instrument_name_engraver",
            "Piano_pedal_align_engraver",
            "Piano_pedal_engraver",
            "Accidental_engraver",
            "Rest_collision_engraver",
            "Grob_pq_engraver",
            "Collision_engraver",
            "Staff_symbol_engraver",
            "Ledger_line_engraver",
            "Key_engraver",
            "Clef_engraver",
            "Ottava_spanner_engraver",
            "Staff_collecting_engraver",
            "Dot_column_engraver",
            "Separating_line_group_engraver",
            "Font_size_engraver",
            "Pure_from_neighbor_engraver",
            "Bar_engraver",
            "Output_property_engraver",
        ]),
        "default_child": "VaticanaVoice",
    },
    "VaticanaVoice": {
        "accepts": set([]),
        "aliases": set([
            "Voice",
        ]),
        "consists": set([
            "Episema_engraver",
            "Vaticana_ligature_engraver",
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
    "Voice": {
        "accepts": set([]),
        "aliases": set([]),
        "consists": set([
            "Instrument_switch_engraver",
            "Tuplet_engraver",
            "Tie_engraver",
            "Slur_engraver",
            "Cluster_spanner_engraver",
            "Phrasing_slur_engraver",
            "Spanner_break_forbid_engraver",
            "Note_spacing_engraver",
            "Rhythmic_column_engraver",
            "Script_column_engraver",
            "Script_engraver",
            "Bend_engraver",
            "Fingering_engraver",
            "Dynamic_align_engraver",
            "Dynamic_engraver",
            "Text_engraver",
            "Part_combine_engraver",
            "Slash_repeat_engraver",
            "Percent_repeat_engraver",
            "Double_percent_repeat_engraver",
            "Chord_tremolo_engraver",
            "New_fingering_engraver",
            "Grace_auto_beam_engraver",
            "Auto_beam_engraver",
            "Grace_beam_engraver",
            "Beam_engraver",
            "Stem_engraver",
            "Rest_engraver",
            "Dots_engraver",
            "Note_heads_engraver",
            "Breathing_sign_engraver",
            "Ligature_bracket_engraver",
            "Glissando_engraver",
            "Note_head_line_engraver",
            "Repeat_tie_engraver",
            "Laissez_vibrer_engraver",
            "Forbid_line_break_engraver",
            "Grob_pq_engraver",
            "Trill_spanner_engraver",
            "Text_spanner_engraver",
            "Multi_measure_rest_engraver",
            "Arpeggio_engraver",
            "Output_property_engraver",
            "Pitched_trill_engraver",
            "Font_size_engraver",
            "Grace_engraver",
        ]),
    },
}
