from abjad.utilities.Duration import Duration
from abjad.parser.LilyPondDuration import LilyPondDuration


lilypond_version = "2.17.9"

current_module = {
    '$current-book': '$current-book',
    '$current-bookpart': '$current-bookpart',
    '$defaultheader': '$defaultheader',
    '$defaultlayout': '$defaultlayout',
    '$defaultmidi': '$defaultmidi',
    '$defaultpaper': '$defaultpaper',
    '%module-public-interface': '%module-public-interface',
    'RemoveEmptyStaves': 'RemoveEmptyStaves',
    'accent': {
        'articulation-type': 'accent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'acciaccatura': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'accidentalStyle': {
        'signature': ('ly:music?', 'symbol-list?',),
        'type': 'ly:music-function?',
    },
    'add-toc-item!': 'add-toc-item!',
    'addChordShape': {
        'signature': ('void?', 'symbol?', 'pair?', 'string-or-pair?',),
        'type': 'ly:music-function?',
    },
    'addInstrumentDefinition': {
        'signature': ('void?', 'string?', 'list?',),
        'type': 'ly:music-function?',
    },
    'addQuote': {
        'signature': ('void?', 'string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'aeolian': 'aeolian',
    'afterGrace': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'afterGraceFraction': 'afterGraceFraction',
    'aikenHeads': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'aikenHeadsMinor': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'allowPageTurn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'allowVoltaHook': {
        'signature': ('void?', 'string?',),
        'type': 'ly:music-function?',
    },
    'alterBroken': {
        'signature': ('ly:music?', 'symbol-list-or-symbol?', 'list?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'appendToTag': {
        'signature': ('ly:music?', 'symbol?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'applyContext': {
        'signature': ('ly:music?', 'procedure?',),
        'type': 'ly:music-function?',
    },
    'applyMusic': {
        'signature': ('ly:music?', 'procedure?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'applyOutput': {
        'signature': ('ly:music?', 'symbol?', 'procedure?',),
        'type': 'ly:music-function?',
    },
    'appoggiatura': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'arpeggio': {
        'name': 'ArpeggioEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'arpeggio-event', 'event',),
    },
    'arpeggioArrowDown': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioArrowUp': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioBracket': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioNormal': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioParenthesis': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'arpeggioParenthesisDashed': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'assertBeamQuant': {
        'signature': ('ly:music?', 'pair?', 'pair?',),
        'type': 'ly:music-function?',
    },
    'assertBeamSlope': {
        'signature': ('ly:music?', 'procedure?',),
        'type': 'ly:music-function?',
    },
    'autoBeamOff': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'autoBeamOn': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'autochange': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'balloonGrobText': {
        'signature': ('ly:music?', 'symbol?', 'number-pair?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'balloonLengthOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'balloonLengthOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'balloonText': {
        'signature': ('ly:music?', 'number-pair?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'banjo-c-tuning': 'banjo-c-tuning',
    'banjo-modal-tuning': 'banjo-modal-tuning',
    'banjo-open-d-tuning': 'banjo-open-d-tuning',
    'banjo-open-dm-tuning': 'banjo-open-dm-tuning',
    'banjo-open-g-tuning': 'banjo-open-g-tuning',
    'bar': {
        'signature': ('ly:music?', 'string?',),
        'type': 'ly:music-function?',
    },
    'barNumberCheck': {
        'signature': ('ly:music?', 'integer?',),
        'type': 'ly:music-function?',
    },
    'baritone-ukulele-tuning': 'baritone-ukulele-tuning',
    'bass-drop-d-tuning': 'bass-drop-d-tuning',
    'bass-five-string-tuning': 'bass-five-string-tuning',
    'bass-four-string-tuning': 'bass-four-string-tuning',
    'bass-six-string-tuning': 'bass-six-string-tuning',
    'bass-tuning': 'bass-tuning',
    'bassFigureExtendersOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'bassFigureExtendersOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'bassFigureStaffAlignmentDown': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bassFigureStaffAlignmentNeutral': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bassFigureStaffAlignmentUp': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'bendAfter': {
        'signature': ('ly:event?', 'real?',),
        'type': 'ly:music-function?',
    },
    'bigger': 1,
    'blackTriangleMarkup': 'blackTriangleMarkup',
    'bongos-style': 'bongos-style',
    'book-bookpart-handler': 'book-bookpart-handler',
    'book-music-handler': 'book-music-handler',
    'book-score-handler': 'book-score-handler',
    'book-text-handler': 'book-text-handler',
    'bookOutputName': {
        'signature': ('void?', 'string?',),
        'type': 'ly:music-function?',
    },
    'bookOutputSuffix': {
        'signature': ('void?', 'string?',),
        'type': 'ly:music-function?',
    },
    'bookpart-music-handler': 'bookpart-music-handler',
    'bookpart-score-handler': 'bookpart-score-handler',
    'bookpart-text-handler': 'bookpart-text-handler',
    'bracketCloseSymbol': {
        'name': 'BeamEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'beam-event', 'span-event',),
    },
    'bracketOpenSymbol': {
        'name': 'BeamEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'beam-event', 'span-event',),
    },
    'break': {
        'name': 'LineBreakEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'line-break-event', 'break-event', 'event',),
    },
    'breakDynamicSpan': {
        'name': 'BreakDynamicSpanEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'break-span-event', 'break-dynamic-span-event', 'event',),
    },
    'breathe': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'breve': LilyPondDuration(Duration(2, 1), None),
    'cadenzaOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'cadenzaOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'cello-tuning': 'cello-tuning',
    'center': 0,
    'chord-shape': 'chord-shape',
    'chord-shape-table': 'chord-shape-table',
    'chordRepeats': {
        'signature': ('ly:music?', 'optional?', 'list?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'chordmodifiers': 'chordmodifiers',
    'clef': {
        'signature': ('ly:music?', 'string?',),
        'type': 'ly:music-function?',
    },
    'coda': {
        'articulation-type': 'coda',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'compoundMeter': {
        'signature': ('ly:music?', 'pair?',),
        'type': 'ly:music-function?',
    },
    'compressFullBarRests': {
        'context-type': 'Score',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'congas-style': 'congas-style',
    'context-mod-music-handler': 'context-mod-music-handler',
    'cr': {
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'cresc': {
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'crescHairpin': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'crescTextCresc': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'crossStaff': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'cueClef': {
        'signature': ('ly:music?', 'string?',),
        'type': 'ly:music-function?',
    },
    'cueClefUnset': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'cueDuring': {
        'signature': ('ly:music?', 'string?', 'ly:dir?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'cueDuringWithClef': {
        'signature': ('ly:music?', 'string?', 'ly:dir?', 'string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'dashBar': {
        'alias': 'staccatissimo',
        'type': 'alias',
    },
    'dashDash': {
        'alias': 'tenuto',
        'type': 'alias',
    },
    'dashDot': {
        'alias': 'staccato',
        'type': 'alias',
    },
    'dashHat': {
        'alias': 'marcato',
        'type': 'alias',
    },
    'dashLarger': {
        'alias': 'accent',
        'type': 'alias',
    },
    'dashPlus': {
        'alias': 'stopped',
        'type': 'alias',
    },
    'dashUnderscore': {
        'alias': 'portato',
        'type': 'alias',
    },
    'deadNote': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'deadNotesOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deadNotesOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'decr': {
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'decresc': {
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'default-fret-table': 'default-fret-table',
    'defaultNoteHeads': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'defaultStringTunings': 'defaultStringTunings',
    'defaultTimeSignature': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'defineBarLine': {
        'signature': ('void?', 'string?', 'list?',),
        'type': 'ly:music-function?',
    },
    'deprecatedcresc': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecateddim': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecatedendcresc': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'deprecatedenddim': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dim': {
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'dimHairpin': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDecr': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDecresc': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dimTextDim': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'displayLilyMusic': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'displayMusic': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'dorian': 'dorian',
    'dotsDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'dotsNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'dotsUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'double-bass-tuning': 'double-bass-tuning',
    'down': -1,
    'downbow': {
        'articulation-type': 'downbow',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'downmordent': {
        'articulation-type': 'downmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'downprall': {
        'articulation-type': 'downprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'drumPitchNames': 'drumPitchNames',
    'drums-style': 'drums-style',
    'dynamicDown': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dynamicNeutral': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'dynamicUp': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'easyHeadsOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'easyHeadsOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'endSpanners': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'endcr': {
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'endcresc': {
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'enddecr': {
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'enddecresc': {
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'enddim': {
        'name': 'DecrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'endincipit': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'episemFinis': {
        'name': 'EpisemaEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'episema-event',),
    },
    'episemInitium': {
        'name': 'EpisemaEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'episema-event',),
    },
    'escapedBiggerSymbol': {
        'name': 'DecrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'decrescendo-event', 'event',),
    },
    'escapedExclamationSymbol': {
        'name': 'CrescendoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'escapedParenthesisCloseSymbol': {
        'name': 'PhrasingSlurEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'phrasing-slur-event',),
    },
    'escapedParenthesisOpenSymbol': {
        'name': 'PhrasingSlurEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'phrasing-slur-event',),
    },
    'escapedSmallerSymbol': {
        'name': 'CrescendoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'span-dynamic-event', 'crescendo-event', 'event',),
    },
    'espressivo': {
        'articulation-type': 'espressivo',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'eventChords': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'expandFullBarRests': {
        'context-type': 'Score',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'expect-error': 'expect-error',
    'f': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'f',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'featherDurations': {
        'signature': ('ly:music?', 'ly:moment?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'fermata': {
        'articulation-type': 'fermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'fermataMarkup': {
        'name': 'MultiMeasureTextEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'multi-measure-text-event',),
    },
    'ff': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'ff',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'fff': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'fff',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ffff': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'ffff',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'fffff': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'fffff',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'flageolet': {
        'articulation-type': 'flageolet',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'footnote': {
        'signature': ('ly:music?', 'optional?', 'cheap-markup?', 'number-pair?', 'cheap-markup?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'four-string-banjo': 'four-string-banjo',
    'fp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'fp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'frenchChords': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'fullJazzExceptions': 'fullJazzExceptions',
    'funkHeads': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'funkHeadsMinor': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'fz': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'fz',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'germanChords': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'glissando': {
        'name': 'GlissandoEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'glissando-event', 'event',),
    },
    'grace': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'grobdescriptions': {
        'signature': ('scheme?', 'list?',),
        'type': 'ly:music-function?',
    },
    'guitar-asus4-tuning': 'guitar-asus4-tuning',
    'guitar-dadgad-tuning': 'guitar-dadgad-tuning',
    'guitar-drop-c-tuning': 'guitar-drop-c-tuning',
    'guitar-drop-d-tuning': 'guitar-drop-d-tuning',
    'guitar-lute-tuning': 'guitar-lute-tuning',
    'guitar-open-d-tuning': 'guitar-open-d-tuning',
    'guitar-open-g-tuning': 'guitar-open-g-tuning',
    'guitar-seven-string-tuning': 'guitar-seven-string-tuning',
    'guitar-tuning': 'guitar-tuning',
    'halfopen': {
        'articulation-type': 'halfopen',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'harmonic': {
        'name': 'HarmonicEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'harmonic-event',),
    },
    'harmonicByFret': {
        'signature': ('ly:music?', 'number?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicByRatio': {
        'signature': ('ly:music?', 'number?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicNote': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'harmonicsOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'harmonicsOn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'hide': {
        'signature': ('ly:music?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'hideNotes': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'hideSplitTiedTabNotes': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'hideStaffSwitch': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'huge': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'ignatzekExceptionMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'ignatzekExceptions': 'ignatzekExceptions',
    'improvisationOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'improvisationOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'inStaffSegno': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'input-file-name': None,
    'instrument-definitions': 'instrument-definitions',
    'instrumentSwitch': {
        'signature': ('ly:music?', 'string?',),
        'type': 'ly:music-function?',
    },
    'inversion': {
        'signature': ('ly:music?', 'ly:pitch?', 'ly:pitch?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'ionian': 'ionian',
    'italianChords': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'keepWithTag': {
        'signature': ('ly:music?', 'symbol-list-or-symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'key': {
        'signature': ('ly:music?', 'optional?', 'ly:pitch?', 'optional?', 'list?',),
        'type': 'ly:music-function?',
    },
    'kievanOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'kievanOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'killCues': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'label': {
        'signature': ('ly:music?', 'symbol?',),
        'type': 'ly:music-function?',
    },
    'laissezVibrer': {
        'name': 'LaissezVibrerEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'laissez-vibrer-event',),
    },
    'language': {
        'signature': ('void?', 'string?',),
        'type': 'ly:music-function?',
    },
    'languageRestore': {
        'signature': ('void?',),
        'type': 'ly:music-function?',
    },
    'languageSaveAndChange': {
        'signature': ('void?', 'string?',),
        'type': 'ly:music-function?',
    },
    'large': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'left': -1,
    'lheel': {
        'articulation-type': 'lheel',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'lineprall': {
        'articulation-type': 'lineprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'locrian': 'locrian',
    'longa': LilyPondDuration(Duration(4, 1), None),
    'longfermata': {
        'articulation-type': 'longfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'ltoe': {
        'articulation-type': 'ltoe',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'lydian': 'lydian',
    'major': 'major',
    'make-dynamic-script': 'make-dynamic-script',
    'make-fretboard-table': 'make-fretboard-table',
    'make-simple-dash-definition': 'make-simple-dash-definition',
    'make-table-of-contents-markup-list': 'make-table-of-contents-markup-list',
    'makeClusters': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'makeDefaultStringTuning': {
        'signature': ('void?', 'symbol?', 'list?',),
        'type': 'ly:music-function?',
    },
    'mandolin-tuning': 'mandolin-tuning',
    'marcato': {
        'articulation-type': 'marcato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'mark': {
        'signature': ('ly:music?', 'optional?', 'scheme?',),
        'type': 'ly:music-function?',
    },
    'maxima': LilyPondDuration(Duration(8, 1), None),
    'melisma': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'melismaEnd': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyDottedOff': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyDottedOn': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyHeadedOff': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mergeDifferentlyHeadedOn': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'mf': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'mf',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'midiDrumPitches': 'midiDrumPitches',
    'minor': 'minor',
    'mixolydian': 'mixolydian',
    'modalInversion': {
        'signature': ('ly:music?', 'ly:pitch?', 'ly:pitch?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'modalTranspose': {
        'signature': ('ly:music?', 'ly:pitch?', 'ly:pitch?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'mordent': {
        'articulation-type': 'mordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'mp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'mp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'musicMap': {
        'signature': ('ly:music?', 'procedure?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'musicQuotes': 'musicQuotes',
    'newSpacingSection': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'noBeam': {
        'name': 'BeamForbidEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'beam-forbid-event',),
    },
    'noBreak': {
        'name': 'LineBreakEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'line-break-event', 'break-event', 'event',),
    },
    'noPageBreak': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'noPageTurn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'normalsize': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'numericTimeSignature': {
        'context-type': 'Staff',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'octaveCheck': {
        'signature': ('ly:music?', 'ly:pitch?',),
        'type': 'ly:music-function?',
    },
    'omit': {
        'signature': ('ly:music?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'once': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'oneVoice': {
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'open': {
        'articulation-type': 'open',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'ottava': {
        'signature': ('ly:music?', 'integer?',),
        'type': 'ly:music-function?',
    },
    'output-def-music-handler': 'output-def-music-handler',
    'output-empty-score-list': 'output-empty-score-list',
    'output-suffix': 'output-suffix',
    'overrideProperty': {
        'signature': ('ly:music?', 'symbol-list?', 'scheme?',),
        'type': 'ly:music-function?',
    },
    'overrideTimeSignatureSettings': {
        'signature': ('ly:music?', 'pair?', 'pair?', 'cheap-list?', 'cheap-list?',),
        'type': 'ly:music-function?',
    },
    'p': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'p',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'pageBreak': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'pageTurn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'palmMute': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'palmMuteOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'palmMuteOn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
    'parallelMusic': {
        'signature': ('void?', 'list?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'parenthesisCloseSymbol': {
        'name': 'SlurEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'slur-event',),
    },
    'parenthesisOpenSymbol': {
        'name': 'SlurEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'slur-event',),
    },
    'parenthesize': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'parser': 'parser',
    'partCombineListener': 'partCombineListener',
    'partcombine': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'partcombineApart': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineApartOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineAutomatic': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineAutomaticOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineChords': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineChordsOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineDown': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'partcombineForce': {
        'signature': ('ly:music?', 'symbol-or-boolean?', 'boolean?',),
        'type': 'ly:music-function?',
    },
    'partcombineSoloI': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloII': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloIIOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineSoloIOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineUnisono': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineUnisonoOnce': {
        'name': 'EventChord',
        'type': 'ly:prob?',
        'types': ('general-music', 'event-chord', 'simultaneous-music',),
    },
    'partcombineUp': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'partial': {
        'signature': ('ly:music?', 'ly:duration?',),
        'type': 'ly:music-function?',
    },
    'partialJazzExceptions': 'partialJazzExceptions',
    'partialJazzMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'percussion-style': 'percussion-style',
    'phrasingSlurDashPattern': {
        'signature': ('ly:music?', 'number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'phrasingSlurDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurDotted': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurHalfDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurHalfSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrasingSlurUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'phrygian': 'phrygian',
    'pipeSymbol': {
        'name': 'BarCheck',
        'type': 'ly:prob?',
        'types': ('general-music', 'bar-check',),
    },
    'pitchedTrill': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'pointAndClickOff': {
        'signature': ('void?',),
        'type': 'ly:music-function?',
    },
    'pointAndClickOn': {
        'signature': ('void?',),
        'type': 'ly:music-function?',
    },
    'pointAndClickTypes': {
        'signature': ('void?', 'symbol-list-or-symbol?',),
        'type': 'ly:music-function?',
    },
    'portato': {
        'articulation-type': 'portato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'powerChordExceptions': 'powerChordExceptions',
    'powerChordSymbol': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'powerChords': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'pp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'pp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ppp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'ppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'pppp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'pppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'ppppp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'ppppp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'prall': {
        'articulation-type': 'prall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'pralldown': {
        'articulation-type': 'pralldown',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'prallmordent': {
        'articulation-type': 'prallmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'prallprall': {
        'articulation-type': 'prallprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'prallup': {
        'articulation-type': 'prallup',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'predefinedFretboardsOff': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'predefinedFretboardsOn': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'pushToTag': {
        'signature': ('ly:music?', 'symbol?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'quoteDuring': {
        'signature': ('ly:music?', 'string?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'relative': {
        'signature': ('ly:music?', 'optional?', 'ly:pitch?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'removeWithTag': {
        'signature': ('ly:music?', 'symbol-list-or-symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'repeatTie': {
        'name': 'RepeatTieEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'repeat-tie-event',),
    },
    'resetRelativeOctave': {
        'signature': ('ly:music?', 'ly:pitch?',),
        'type': 'ly:music-function?',
    },
    'retrograde': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'reverseturn': {
        'articulation-type': 'reverseturn',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'revertTimeSignatureSettings': {
        'signature': ('ly:music?', 'pair?',),
        'type': 'ly:music-function?',
    },
    'rfz': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'rfz',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'rheel': {
        'articulation-type': 'rheel',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'right': 1,
    'rightHandFinger': {
        'signature': ('ly:event?', 'number-or-string?',),
        'type': 'ly:music-function?',
    },
    'rtoe': {
        'articulation-type': 'rtoe',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'sacredHarpHeads': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'sacredHarpHeadsMinor': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'scaleDurations': {
        'signature': ('ly:music?', 'fraction?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'segno': {
        'articulation-type': 'segno',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'semiGermanChords': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'setDefaultDurationToQuarter': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'settingsFrom': {
        'signature': ('scheme?', 'optional?', 'symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'sf': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'sf',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sff': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'sff',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sfp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'sfp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'sfz': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'sfz',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'shape': {
        'signature': ('ly:music?', 'list?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'shiftDurations': {
        'signature': ('ly:music?', 'integer?', 'integer?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'shiftOff': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOn': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOnn': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shiftOnnn': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'shortfermata': {
        'articulation-type': 'shortfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'showSplitTiedTabNotes': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'showStaffSwitch': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'signumcongruentiae': {
        'articulation-type': 'signumcongruentiae',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'single': {
        'signature': ('ly:music?', 'ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'skip': {
        'signature': ('ly:music?', 'ly:duration?',),
        'type': 'ly:music-function?',
    },
    'slashedGrace': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'slurDashPattern': {
        'signature': ('ly:music?', 'number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'slurDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurDotted': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurHalfDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurHalfSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'slurUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'small': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'smaller': -1,
    'snappizzicato': {
        'articulation-type': 'snappizzicato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'sostenutoOff': {
        'name': 'SostenutoEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'sostenuto-event',),
    },
    'sostenutoOn': {
        'name': 'SostenutoEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'sostenuto-event',),
    },
    'southernHarmonyHeads': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'southernHarmonyHeadsMinor': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'sp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'sp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'spacingTweaks': {
        'signature': ('ly:music?', 'list?',),
        'type': 'ly:music-function?',
    },
    'spp': {
        'name': 'AbsoluteDynamicEvent',
        'text': 'spp',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'dynamic-event', 'absolute-dynamic-event',),
    },
    'staccatissimo': {
        'articulation-type': 'staccatissimo',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'staccato': {
        'articulation-type': 'staccato',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'start': -1,
    'startAcciaccaturaMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startAppoggiaturaMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startGraceMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startGraceSlur': {
        'name': 'SlurEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'slur-event',),
    },
    'startGroup': {
        'name': 'NoteGroupingEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'note-grouping-event',),
    },
    'startMeasureCount': {
        'name': 'MeasureCounterEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'measure-counter-event', 'span-event', 'event',),
    },
    'startSlashedGraceMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'startStaff': {
        'name': 'StaffSpanEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'span-event', 'staff-span-event',),
    },
    'startTextSpan': {
        'name': 'TextSpanEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'text-span-event',),
    },
    'startTrillSpan': {
        'name': 'TrillSpanEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'trill-span-event',),
    },
    'stemDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stemNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stemUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'stop': 1,
    'stopAcciaccaturaMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopAppoggiaturaMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopGraceMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopGraceSlur': {
        'name': 'SlurEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'slur-event',),
    },
    'stopGroup': {
        'name': 'NoteGroupingEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'note-grouping-event',),
    },
    'stopMeasureCount': {
        'name': 'MeasureCounterEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'measure-counter-event', 'span-event', 'event',),
    },
    'stopSlashedGraceMusic': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'stopStaff': {
        'name': 'StaffSpanEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'event', 'span-event', 'staff-span-event',),
    },
    'stopTextSpan': {
        'name': 'TextSpanEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'text-span-event',),
    },
    'stopTrillSpan': {
        'name': 'TrillSpanEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'span-event', 'event', 'trill-span-event',),
    },
    'stopped': {
        'articulation-type': 'stopped',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'storePredefinedDiagram': {
        'signature': ('void?', 'hash-table?', 'ly:music?', 'pair?', 'string-or-pair?',),
        'type': 'ly:music-function?',
    },
    'stringTuning': {
        'signature': ('scheme?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'styledNoteHeads': {
        'signature': ('ly:music?', 'symbol?', 'symbol-list-or-symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'sustainOff': {
        'name': 'SustainEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'sustain-event',),
    },
    'sustainOn': {
        'name': 'SustainEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'sustain-event',),
    },
    'tabChordRepeats': {
        'signature': ('ly:music?', 'optional?', 'list?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'tabChordRepetition': {
        'signature': ('void?',),
        'type': 'ly:music-function?',
    },
    'tabFullNotation': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'table-of-contents-markup-list': 'table-of-contents-markup-list',
    'tag': {
        'signature': ('ly:music?', 'symbol-list-or-symbol?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'teeny': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'temporary': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'tenor-ukulele-tuning': 'tenor-ukulele-tuning',
    'tenuto': {
        'articulation-type': 'tenuto',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'textLengthOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'textLengthOn': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'textSpannerDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'textSpannerNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'textSpannerUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'thumb': {
        'articulation-type': 'thumb',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'tieDashPattern': {
        'signature': ('ly:music?', 'number?', 'number?',),
        'type': 'ly:music-function?',
    },
    'tieDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieDotted': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieHalfDashed': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieHalfSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieSolid': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tieUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tildeSymbol': {
        'name': 'TieEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'tie-event', 'event',),
    },
    'timbales-style': 'timbales-style',
    'time': {
        'signature': ('ly:music?', 'optional?', 'number-list?', 'fraction?',),
        'type': 'ly:music-function?',
    },
    'times': {
        'signature': ('ly:music?', 'fraction?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'tiny': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'toc-items': 'toc-items',
    'tocItem': {
        'signature': ('ly:music?', 'cheap-markup?',),
        'type': 'ly:music-function?',
    },
    'tocItemWithDotsMarkup': 'tocItemWithDotsMarkup',
    'toplevel-book-handler': 'toplevel-book-handler',
    'toplevel-bookpart-handler': 'toplevel-bookpart-handler',
    'toplevel-bookparts': 'toplevel-bookparts',
    'toplevel-music-handler': 'toplevel-music-handler',
    'toplevel-score-handler': 'toplevel-score-handler',
    'toplevel-scores': 'toplevel-scores',
    'toplevel-text-handler': 'toplevel-text-handler',
    'transpose': {
        'signature': ('ly:music?', 'ly:pitch?', 'ly:pitch?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'transposedCueDuring': {
        'signature': ('ly:music?', 'string?', 'ly:dir?', 'ly:pitch?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'transposition': {
        'signature': ('ly:music?', 'ly:pitch?',),
        'type': 'ly:music-function?',
    },
    'treCorde': {
        'name': 'UnaCordaEvent',
        'span-direction': 1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'una-corda-event',),
    },
    'trill': {
        'articulation-type': 'trill',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'tupletDown': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tupletNeutral': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'tupletUp': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'turn': {
        'articulation-type': 'turn',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'tweak': {
        'signature': ('ly:music?', 'symbol-list-or-symbol?', 'scheme?', 'symbol-list-or-music?',),
        'type': 'ly:music-function?',
    },
    'ukulele-d-tuning': 'ukulele-d-tuning',
    'ukulele-tuning': 'ukulele-tuning',
    'unHideNotes': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'unaCorda': {
        'name': 'UnaCordaEvent',
        'span-direction': -1,
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'pedal-event', 'una-corda-event',),
    },
    'undo': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'unfoldRepeats': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'up': 1,
    'upbow': {
        'articulation-type': 'upbow',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'upmordent': {
        'articulation-type': 'upmordent',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'upprall': {
        'articulation-type': 'upprall',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'varcoda': {
        'articulation-type': 'varcoda',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'version-seen': 'version-seen',
    'verylongfermata': {
        'articulation-type': 'verylongfermata',
        'name': 'ArticulationEvent',
        'type': 'ly:prob?',
        'types': ('general-music', 'post-event', 'event', 'articulation-event', 'script-event',),
    },
    'viola-tuning': 'viola-tuning',
    'violin-tuning': 'violin-tuning',
    'voiceFour': {
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceFourStyle': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceNeutralStyle': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceOne': {
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceOneStyle': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceThree': {
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceThreeStyle': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'voiceTwo': {
        'context-type': 'Voice',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'voiceTwoStyle': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'void': {
        'signature': ('void?', 'scheme?',),
        'type': 'ly:music-function?',
    },
    'walkerHeads': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'walkerHeadsMinor': {
        'context-type': 'Bottom',
        'name': 'ContextSpeccedMusic',
        'type': 'ly:prob?',
        'types': ('context-specification', 'general-music', 'music-wrapper-music',),
    },
    'whiteTriangleMarkup': 'whiteTriangleMarkup',
    'withMusicProperty': {
        'signature': ('ly:music?', 'symbol?', 'scheme?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'xNote': {
        'signature': ('ly:music?', 'ly:music?',),
        'type': 'ly:music-function?',
    },
    'xNotesOff': {
        'name': 'SequentialMusic',
        'type': 'ly:prob?',
        'types': ('general-music', 'sequential-music',),
    },
    'xNotesOn': {
        'signature': ('ly:music?',),
        'type': 'ly:music-function?',
    },
}
