#! /usr/bin/env python

import os

os.system('clear')
for filename in os.listdir('.'):
   if filename.startswith('test_'):
      old_filename = filename
      new_filename = old_filename.replace('NumericPitch', 'NumberedChromaticPitch')
      command = 'svn mv %s %s' % (old_filename, new_filename)
      os.system(command)
